### ISSUE TITLE
Can't open in newest xcode Version 9.1 (9B55)

### ISSUE THREAD

**Issue by fallenleavesguy** [iOSAppDevelopmentwithSwiftinAction/Chapter3#2]
Can't open in newest xcode Version 9.1 (9B55)

Is overloading operator and generics example wrong ?

**Comment by fallenleavesguy** [comment]
online example is right, I can't declare an overloading in extension(in book)

**Comment by iOSAppDevelopmentwithSwiftinAction** [comment]
Hi yeluoqiuzhi, sorry I've just noticed your post! I'm sure you've probably solved this by now, but if it's still niggling at you, someone else [asked a question](https://forums.manning.com/posts/list/42132.page) about operator overloading over at the forum for the book - perhaps this is related to your problem?
