### ISSUE TITLE
Getting error 'couldn't load settings from contents.xcplayground' in Xcode 9.2

### ISSUE THREAD

**Issue by L10YD1E** [iOSAppDevelopmentwithSwiftinAction/Chapter3#3]
Hi,
 
 I am working through the examples from the book in the latest version of Xcode (9.2 at time of writing) and am unable to open the Chapter 3 playground. I am getting an error dialogue box with the text:

'Couldn't load settings from contents.xcplayground'

I have downloaded multiple times in different locations to no avail.

**Comment by L10YD1E** [comment]
Fixed my issue, from deducing how a playground package should be structured from looking at the Chapter 2 package, I created my own contents.xcplayground and added it to the package. The contents of the file is below if anyone else wants to create their own if the issue isn't fixed in the repository (right-click Chapter3.playground > show package contents > paste in your contents.xcplayground file in with the below content):

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<playground version='6.0' target-platform='ios' display-mode='raw'>
    <pages>
        <page name='Distance'/>
        <page name='DistanceExtensions'/>
        <page name='Extensions'/>
        <page name='Table of Contents'/>
        <page name='TelephoneClassInheritance'/>
        <page name='TelephoneProtocols'/>
    </pages>
</playground>
```

**Comment by iOSAppDevelopmentwithSwiftinAction** [comment]
Hi L10YD1E, sorry I've just noticed this issue. For future reference, I keep a closer eye on the forum for the book here: https://forums.manning.com/forums/ios-development-with-swift-grummitt

Someone else posted about this issue [here](https://forums.manning.com/posts/list/42681.page) and it should now be resolved. Good sleuthing by the way, sorting the issue yourself!
